-- Gringolês — seed do word_bank (307 palavras). Rodar após schema.sql.
-- Idempotente: ON CONFLICT DO NOTHING.
INSERT INTO public.word_bank (bank_id,en,pt,phonetic_br,ipa,example_en,example_pt,emoji,category,active) VALUES
('seed-0','Water','Água','uóra','/ˈwɔːtər/','Can I have some water, please?','Posso beber um pouco de água, por favor?','💧','Essenciais',true),
('seed-1','Food','Comida','fúd','/fuːd/','Brazilian food is amazing.','A comida brasileira é incrível.','🍛','Essenciais',true),
('seed-2','Hello','Olá','helôu','/həˈloʊ/','Hello! How are you?','Olá! Como você está?','👋','Essenciais',true),
('seed-3','Thank you','Obrigado(a)','thénk iú','/ˈθæŋk juː/','Thank you very much!','Muito obrigado!','🙏','Essenciais',true),
('seed-4','Please','Por favor','plíz','/pliːz/','A coffee, please.','Um café, por favor.','☕','Essenciais',true),
('seed-5','Sorry','Desculpa','sóri','/ˈsɒri/','Sorry, I am late.','Desculpa, estou atrasado.','😅','Essenciais',true),
('seed-6','Yes','Sim','iés','/jes/','Yes, I speak English.','Sim, eu falo inglês.','✅','Essenciais',true),
('seed-7','No','Não','nôu','/noʊ/','No, thank you.','Não, obrigado.','🚫','Essenciais',true),
('seed-8','House','Casa','ráus','/haʊs/','My house is near the beach.','Minha casa é perto da praia.','🏠','Casa',true),
('seed-9','Bed','Cama','béd','/bed/','I go to bed at 10pm.','Vou para a cama às 22h.','🛏️','Casa',true),
('seed-10','Kitchen','Cozinha','kítchen','/ˈkɪtʃɪn/','Mom is in the kitchen.','Mamãe está na cozinha.','🍳','Casa',true),
('seed-11','Door','Porta','dór','/dɔːr/','Close the door, please.','Feche a porta, por favor.','🚪','Casa',true),
('seed-12','Window','Janela','uíndou','/ˈwɪndoʊ/','Open the window.','Abra a janela.','🪟','Casa',true),
('seed-13','Apple','Maçã','épou','/ˈæpəl/','An apple a day keeps the doctor away.','Uma maçã por dia mantém o médico longe.','🍎','Comida',true),
('seed-14','Bread','Pão','bréd','/bred/','I eat bread every morning.','Como pão toda manhã.','🍞','Comida',true),
('seed-15','Cheese','Queijo','chíz','/tʃiːz/','I love cheese bread (pão de queijo).','Eu amo pão de queijo.','🧀','Comida',true),
('seed-16','Chicken','Frango','tchíquen','/ˈtʃɪkɪn/','Grilled chicken with rice.','Frango grelhado com arroz.','🍗','Comida',true),
('seed-17','Coffee','Café','cófi','/ˈkɔːfi/','Brazilian coffee is the best.','O café brasileiro é o melhor.','☕','Comida',true),
('seed-18','Airport','Aeroporto','érport','/ˈerpɔːrt/','The airport is far from here.','O aeroporto é longe daqui.','✈️','Viagem',true),
('seed-19','Ticket','Passagem / Bilhete','tíquêt','/ˈtɪkɪt/','I bought two tickets.','Comprei duas passagens.','🎫','Viagem',true),
('seed-20','Hotel','Hotel','houtél','/hoʊˈtel/','Our hotel has a pool.','Nosso hotel tem piscina.','🏨','Viagem',true),
('seed-21','Beach','Praia','bítch','/biːtʃ/','Copacabana beach is famous.','A praia de Copacabana é famosa.','🏖️','Viagem',true),
('seed-22','Map','Mapa','mép','/mæp/','Can you show me on the map?','Você pode me mostrar no mapa?','🗺️','Viagem',true),
('seed-23','To eat','Comer','tu ít','/tuː iːt/','I want to eat pizza.','Quero comer pizza.','🍕','Verbos',true),
('seed-24','To drink','Beber','tu drínk','/tuː drɪŋk/','I drink water every day.','Bebo água todo dia.','🥤','Verbos',true),
('seed-25','To go','Ir','tu gôu','/tuː ɡoʊ/','I go to work by bus.','Vou ao trabalho de ônibus.','🚌','Verbos',true),
('seed-26','To speak','Falar','tu spík','/tuː spiːk/','I speak Portuguese and English.','Falo português e inglês.','🗣️','Verbos',true),
('seed-27','To learn','Aprender','tu lérn','/tuː lɜːrn/','I learn English every day.','Aprendo inglês todo dia.','📚','Verbos',true),
('seed-28','To work','Trabalhar','tu uórk','/tuː wɜːrk/','She works from home.','Ela trabalha de casa.','💼','Verbos',true),
('seed-29','To love','Amar','tu lâv','/tuː lʌv/','I love my family.','Eu amo minha família.','❤️','Verbos',true),
('seed-30','To need','Precisar','tu níd','/tuː niːd/','I need help.','Preciso de ajuda.','🆘','Verbos',true),
('seed-31','Morning','Manhã','mórnin','/ˈmɔːrnɪŋ/','Good morning!','Bom dia!','🌅','Rotina',true),
('seed-32','Night','Noite','náit','/naɪt/','Good night!','Boa noite!','🌙','Rotina',true),
('seed-33','Today','Hoje','tudêi','/təˈdeɪ/','Today is a great day.','Hoje é um ótimo dia.','📅','Rotina',true),
('seed-34','Tomorrow','Amanhã','tumórou','/təˈmɔːroʊ/','See you tomorrow!','Te vejo amanhã!','🔜','Rotina',true),
('seed-35','Friend','Amigo(a)','frénd','/frend/','He is my best friend.','Ele é meu melhor amigo.','🧑‍🤝‍🧑','Pessoas',true),
('seed-36','Family','Família','fémeli','/ˈfæməli/','My family is big.','Minha família é grande.','👨‍👩‍👧‍👦','Pessoas',true),
('seed-37','Dog','Cachorro','dóg','/dɔːɡ/','My dog is very friendly.','Meu cachorro é muito amigável.','🐶','Pessoas',true),
('seed-38','Cat','Gato','két','/kæt/','The cat is sleeping.','O gato está dormindo.','🐱','Pessoas',true),
('seed-39','Computer','Computador','compiúra','/kəmˈpjuːtər/','I work on my computer.','Trabalho no meu computador.','💻','Tech',true),
('seed-40','Phone','Telefone / Celular','fôun','/foʊn/','My phone is charging.','Meu celular está carregando.','📱','Tech',true),
('seed-41','Money','Dinheiro','mâni','/ˈmʌni/','I need to save money.','Preciso guardar dinheiro.','💰','Tech',true),
('seed-42','Time','Tempo / Hora','táim','/taɪm/','What time is it?','Que horas são?','⏰','Rotina',true),
('seed-43','Happy','Feliz','répi','/ˈhæpi/','I am happy today.','Estou feliz hoje.','😄','Adjetivos',true),
('seed-44','Beautiful','Lindo(a)','biúrifou','/ˈbjuːtɪfəl/','Rio is a beautiful city.','O Rio é uma cidade linda.','🌆','Adjetivos',true),
('seed-45','Big','Grande','bíg','/bɪɡ/','An elephant is big.','Um elefante é grande.','🐘','Adjetivos',true),
('seed-46','Small','Pequeno(a)','smól','/smɔːl/','I live in a small town.','Moro numa cidade pequena.','🐭','Adjetivos',true),
('seed-47','Fast','Rápido','fést','/fæst/','This car is very fast.','Este carro é muito rápido.','🏎️','Adjetivos',true),
('seed-48','Easy','Fácil','ízi','/ˈiːzi/','English is easy with practice.','Inglês é fácil com prática.','👍','Adjetivos',true),
('bank-0','Goodbye','Tchau','gudbái','/ˌɡʊdˈbaɪ/','Goodbye! See you soon.','Tchau! Até breve.','👋','Essenciais',true),
('bank-1','Good morning','Bom dia','gud mórnin','/ˌɡʊd ˈmɔːrnɪŋ/','Good morning, everyone!','Bom dia a todos!','🌅','Essenciais',true),
('bank-2','Good night','Boa noite','gud náit','/ˌɡʊd ˈnaɪt/','Good night, sleep well.','Boa noite, durma bem.','🌙','Essenciais',true),
('bank-3','Welcome','Bem-vindo(a)','uéucam','/ˈwelkəm/','Welcome to Brazil!','Bem-vindo ao Brasil!','🤗','Essenciais',true),
('bank-4','Excuse me','Com licença','eksquiúz mi','/ɪkˈskjuːz miː/','Excuse me, where is the bank?','Com licença, onde fica o banco?','🙋','Essenciais',true),
('bank-5','Help','Ajuda / Socorro','hélp','/help/','I need help, please.','Preciso de ajuda, por favor.','🆘','Essenciais',true),
('bank-6','Bathroom','Banheiro','béthrum','/ˈbæθruːm/','Where is the bathroom?','Onde fica o banheiro?','🚻','Essenciais',true),
('bank-7','Hospital','Hospital','róspitau','/ˈhɒspɪtəl/','The hospital is near here.','O hospital é perto daqui.','🏥','Essenciais',true),
('bank-8','Police','Polícia','polís','/pəˈliːs/','Call the police!','Chame a polícia!','🚔','Essenciais',true),
('bank-9','Pharmacy','Farmácia','fármesi','/ˈfɑːrməsi/','Is there a pharmacy nearby?','Há uma farmácia por perto?','💊','Essenciais',true),
('bank-10','Street','Rua','strít','/striːt/','What street is this?','Que rua é esta?','🛣️','Essenciais',true),
('bank-11','City','Cidade','síri','/ˈsɪti/','São Paulo is a big city.','São Paulo é uma cidade grande.','🏙️','Essenciais',true),
('bank-12','Country','País','cântri','/ˈkʌntri/','Brazil is my country.','O Brasil é meu país.','🌎','Essenciais',true),
('bank-13','Price','Preço','práis','/praɪs/','What is the price?','Qual é o preço?','🏷️','Essenciais',true),
('bank-14','Free','Grátis / Livre','frí','/friː/','The tour is free.','O passeio é grátis.','🎁','Essenciais',true),
('bank-15','Open','Aberto','ôupen','/ˈoʊpən/','The store is open.','A loja está aberta.','🔓','Essenciais',true),
('bank-16','Closed','Fechado','clôuzd','/kloʊzd/','Sorry, we are closed.','Desculpe, estamos fechados.','🔒','Essenciais',true),
('bank-17','Now','Agora','náu','/naʊ/','Come here now.','Venha aqui agora.','⏱️','Essenciais',true),
('bank-18','Later','Depois / Mais tarde','lêirer','/ˈleɪtər/','See you later!','Te vejo depois!','🔜','Essenciais',true),
('bank-19','Here','Aqui','rír','/hɪr/','Sit here, please.','Sente-se aqui, por favor.','📍','Essenciais',true),
('bank-20','There','Lá / Ali','dér','/ðer/','The book is over there.','O livro está lá.','👉','Essenciais',true),
('bank-21','Table','Mesa','têibou','/ˈteɪbəl/','Dinner is on the table.','O jantar está na mesa.','🍽️','Casa',true),
('bank-22','Chair','Cadeira','tchér','/tʃer/','Sit on the chair.','Sente-se na cadeira.','🪑','Casa',true),
('bank-23','Sofa','Sofá','sôufa','/ˈsoʊfə/','The cat sleeps on the sofa.','O gato dorme no sofá.','🛋️','Casa',true),
('bank-24','Lamp','Luminária / Abajur','lémp','/læmp/','Turn on the lamp.','Acenda o abajur.','💡','Casa',true),
('bank-25','Mirror','Espelho','míror','/ˈmɪrər/','Look in the mirror.','Olhe no espelho.','🪞','Casa',true),
('bank-26','Pillow','Travesseiro','pílou','/ˈpɪloʊ/','My pillow is soft.','Meu travesseiro é macio.','🛌','Casa',true),
('bank-27','Blanket','Cobertor','blénkêt','/ˈblæŋkɪt/','Take a blanket, it is cold.','Pegue um cobertor, está frio.','🛏️','Casa',true),
('bank-28','Towel','Toalha','táuau','/ˈtaʊəl/','Bring a clean towel.','Traga uma toalha limpa.','🧖','Casa',true),
('bank-29','Shower','Chuveiro / Banho','cháuar','/ˈʃaʊər/','I take a shower daily.','Tomo banho todo dia.','🚿','Casa',true),
('bank-30','Stove','Fogão','stôuv','/stoʊv/','Rice is on the stove.','O arroz está no fogão.','🍳','Casa',true),
('bank-31','Fridge','Geladeira','frídge','/frɪdʒ/','The milk is in the fridge.','O leite está na geladeira.','🧊','Casa',true),
('bank-32','Sink','Pia','sínk','/sɪŋk/','Wash your hands in the sink.','Lave as mãos na pia.','🚰','Casa',true),
('bank-33','Key','Chave','kí','/kiː/','I lost my house key.','Perdi a chave de casa.','🔑','Casa',true),
('bank-34','Wall','Parede','uól','/wɔːl/','The photo is on the wall.','A foto está na parede.','🧱','Casa',true),
('bank-35','Floor','Chão / Andar','flór','/flɔːr/','We live on the third floor.','Moramos no terceiro andar.','🏢','Casa',true),
('bank-36','Ceiling','Teto','sílin','/ˈsiːlɪŋ/','The lamp hangs from the ceiling.','A lâmpada pende do teto.','🏠','Casa',true),
('bank-37','Garden','Jardim','gárden','/ˈɡɑːrdən/','Kids play in the garden.','As crianças brincam no jardim.','🌻','Casa',true),
('bank-38','Bedroom','Quarto','bédrum','/ˈbedruːm/','My bedroom is small.','Meu quarto é pequeno.','🛏️','Casa',true),
('bank-39','Living room','Sala de estar','lívin rum','/ˈlɪvɪŋ ruːm/','We watch TV in the living room.','Assistimos TV na sala.','📺','Casa',true),
('bank-40','Rice','Arroz','ráis','/raɪs/','Rice and beans, please.','Arroz e feijão, por favor.','🍚','Comida',true),
('bank-41','Beans','Feijão','bíns','/biːnz/','Black beans are typical.','Feijão preto é típico.','🫘','Comida',true),
('bank-42','Meat','Carne','mít','/miːt/','Brazilian barbecue meat is great.','A carne do churrasco é ótima.','🥩','Comida',true),
('bank-43','Fish','Peixe','físh','/fɪʃ/','Grilled fish is healthy.','Peixe grelhado é saudável.','🐟','Comida',true),
('bank-44','Egg','Ovo','ég','/eɡ/','Two fried eggs, please.','Dois ovos fritos, por favor.','🍳','Comida',true),
('bank-45','Milk','Leite','míuk','/mɪlk/','A glass of milk.','Um copo de leite.','🥛','Comida',true),
('bank-46','Sugar','Açúcar','chúgar','/ˈʃʊɡər/','No sugar in my coffee.','Sem açúcar no meu café.','🍬','Comida',true),
('bank-47','Salt','Sal','sólt','/sɔːlt/','Add a little salt.','Adicione um pouco de sal.','🧂','Comida',true),
('bank-48','Butter','Manteiga','bárer','/ˈbʌtər/','Bread with butter.','Pão com manteiga.','🧈','Comida',true),
('bank-49','Juice','Suco','dçúss','/dʒuːs/','Fresh orange juice.','Suco de laranja fresco.','🧃','Comida',true),
('bank-50','Tea','Chá','tí','/tiː/','A hot cup of tea.','Uma xícara de chá quente.','🍵','Comida',true),
('bank-51','Beer','Cerveja','bír','/bɪr/','A cold beer, please.','Uma cerveja gelada, por favor.','🍺','Comida',true),
('bank-52','Cake','Bolo','kêik','/keɪk/','Chocolate cake for dessert.','Bolo de chocolate de sobremesa.','🍰','Comida',true),
('bank-53','Ice cream','Sorvete','áis crím','/ˈaɪs kriːm/','Ice cream on a hot day.','Sorvete num dia quente.','🍨','Comida',true),
('bank-54','Fruit','Fruta','frút','/fruːt/','Eat more fruit.','Coma mais fruta.','🍇','Comida',true),
('bank-55','Banana','Banana','benéna','/bəˈnænə/','A banana for breakfast.','Uma banana no café da manhã.','🍌','Comida',true),
('bank-56','Orange','Laranja','órrendge','/ˈɒrɪndʒ/','An orange a day.','Uma laranja por dia.','🍊','Comida',true),
('bank-57','Lunch','Almoço','lântch','/lʌntʃ/','Lunch is at noon.','O almoço é ao meio-dia.','🍱','Comida',true),
('bank-58','Dinner','Jantar','dîner','/ˈdɪnər/','Dinner with my family.','Jantar com minha família.','🍷','Comida',true),
('bank-59','Breakfast','Café da manhã','brékfest','/ˈbrekfəst/','Breakfast is ready.','O café da manhã está pronto.','🥞','Comida',true),
('bank-60','Snack','Lanche','snék','/snæk/','A quick afternoon snack.','Um lanche rápido à tarde.','🥪','Comida',true),
('bank-61','Restaurant','Restaurante','réstaurant','/ˈrestərɒnt/','This restaurant is excellent.','Este restaurante é excelente.','🍴','Comida',true),
('bank-62','Plane','Avião','plêin','/pleɪn/','Our plane leaves at six.','Nosso avião sai às seis.','🛫','Viagem',true),
('bank-63','Bus','Ônibus','bâs','/bʌs/','Take the bus downtown.','Pegue o ônibus ao centro.','🚌','Viagem',true),
('bank-64','Train','Trem','trêin','/treɪn/','The train is on time.','O trem está no horário.','🚆','Viagem',true),
('bank-65','Taxi','Táxi','téksi','/ˈtæksi/','Call a taxi, please.','Chame um táxi, por favor.','🚕','Viagem',true),
('bank-66','Car','Carro','cár','/kɑːr/','My car is new.','Meu carro é novo.','🚗','Viagem',true),
('bank-67','Passport','Passaporte','pésport','/ˈpæspɔːrt/','Do not forget your passport.','Não esqueça seu passaporte.','🛂','Viagem',true),
('bank-68','Luggage','Bagagem','lâguedge','/ˈlʌɡɪdʒ/','My luggage is heavy.','Minha bagagem está pesada.','🧳','Viagem',true),
('bank-69','Flight','Voo','fláit','/flaɪt/','Our flight is delayed.','Nosso voo está atrasado.','✈️','Viagem',true),
('bank-70','Seat','Assento','sít','/siːt/','This is my seat.','Este é meu assento.','💺','Viagem',true),
('bank-71','Exit','Saída','égzit','/ˈeɡzɪt/','Where is the exit?','Onde fica a saída?','🚪','Viagem',true),
('bank-72','Entrance','Entrada','éntrens','/ˈentrəns/','Meet me at the entrance.','Encontre-me na entrada.','🚶','Viagem',true),
('bank-73','Center','Centro','sénter','/ˈsentər/','The mall is in the center.','O shopping fica no centro.','🏬','Viagem',true),
('bank-74','Bridge','Ponte','brídge','/brɪdʒ/','Cross the bridge.','Atravesse a ponte.','🌉','Viagem',true),
('bank-75','Island','Ilha','áilend','/ˈaɪlənd/','A beautiful tropical island.','Uma linda ilha tropical.','🏝️','Viagem',true),
('bank-76','Trip','Viagem (curta)','tríp','/trɪp/','Have a nice trip!','Boa viagem!','🧭','Viagem',true),
('bank-77','Vacation','Férias','veikêichan','/veɪˈkeɪʃən/','We are on vacation.','Estamos de férias.','🏖️','Viagem',true),
('bank-78','Suitcase','Mala','sútkeis','/ˈsuːtkeɪs/','Pack your suitcase.','Arrume sua mala.','💼','Viagem',true),
('bank-79','Station','Estação','stêichan','/ˈsteɪʃən/','The station is far.','A estação é longe.','🚉','Viagem',true),
('bank-80','Driver','Motorista','dráiver','/ˈdraɪvər/','The driver is friendly.','O motorista é simpático.','🚚','Viagem',true),
('bank-81','To buy','Comprar','tu bái','/tuː baɪ/','I want to buy shoes.','Quero comprar sapatos.','🛍️','Verbos',true),
('bank-82','To sell','Vender','tu sél','/tuː sel/','He sells fresh fruit.','Ele vende fruta fresca.','💰','Verbos',true),
('bank-83','To pay','Pagar','tu pêi','/tuː peɪ/','Can I pay by card?','Posso pagar no cartão?','💳','Verbos',true),
('bank-84','To ask','Pedir / Perguntar','tu ésk','/tuː æsk/','Ask for help.','Peça ajuda.','❓','Verbos',true),
('bank-85','To answer','Responder','tu énser','/tuː ˈænsər/','Answer my question.','Responda minha pergunta.','💬','Verbos',true),
('bank-86','To read','Ler','tu ríd','/tuː riːd/','I read every night.','Leio toda noite.','📖','Verbos',true),
('bank-87','To write','Escrever','tu ráit','/tuː raɪt/','Write your name here.','Escreva seu nome aqui.','✍️','Verbos',true),
('bank-88','To listen','Ouvir / Escutar','tu lícen','/tuː ˈlɪsən/','Listen to music daily.','Ouça música todo dia.','🎧','Verbos',true),
('bank-89','To watch','Assistir','tu uótch','/tuː wɒtʃ/','We watch movies together.','Assistimos filmes juntos.','🎬','Verbos',true),
('bank-90','To play','Jogar / Tocar','tu plêi','/tuː pleɪ/','Kids play soccer.','As crianças jogam futebol.','⚽','Verbos',true),
('bank-91','To run','Correr','tu rân','/tuː rʌn/','I run every morning.','Corro toda manhã.','🏃','Verbos',true),
('bank-92','To walk','Andar / Caminhar','tu uók','/tuː wɔːk/','We walk to the park.','Andamos até o parque.','🚶','Verbos',true),
('bank-93','To sleep','Dormir','tu slíp','/tuː sliːp/','Babies sleep a lot.','Bebês dormem muito.','😴','Verbos',true),
('bank-94','To wake up','Acordar','tu uêik âp','/tuː weɪk ʌp/','I wake up at six.','Acordo às seis.','⏰','Verbos',true),
('bank-95','To cook','Cozinhar','tu cûk','/tuː kʊk/','Dad cooks on Sundays.','Papai cozinha aos domingos.','👨‍🍳','Verbos',true),
('bank-96','To clean','Limpar','tu clín','/tuː kliːn/','Clean your room.','Limpe seu quarto.','🧹','Verbos',true),
('bank-97','To open','Abrir','tu ôupen','/tuː ˈoʊpən/','Open the window.','Abra a janela.','🪟','Verbos',true),
('bank-98','To close','Fechar','tu clôuz','/tuː kloʊz/','Close the door.','Feche a porta.','🚪','Verbos',true),
('bank-99','To start','Começar','tu stárt','/tuː stɑːrt/','Classes start in March.','As aulas começam em março.','🏁','Verbos',true),
('bank-100','To finish','Terminar','tu fínish','/tuː ˈfɪnɪʃ/','Finish your homework.','Termine sua lição.','✅','Verbos',true),
('bank-101','To help','Ajudar','tu hélp','/tuː help/','Can you help me?','Você pode me ajudar?','🤝','Verbos',true),
('bank-102','To like','Gostar','tu láik','/tuː laɪk/','I like chocolate.','Gosto de chocolate.','👍','Verbos',true),
('bank-103','To want','Querer','tu uónt','/tuː wɒnt/','I want to travel.','Quero viajar.','🌟','Verbos',true),
('bank-104','To think','Pensar / Achar','tu thínk','/tuː θɪŋk/','I think it is easy.','Acho que é fácil.','💭','Verbos',true),
('bank-105','Week','Semana','uík','/wiːk/','See you next week.','Te vejo semana que vem.','📅','Rotina',true),
('bank-106','Weekend','Fim de semana','uíkend','/ˌwiːkˈend/','What a great weekend!','Que ótimo fim de semana!','🎉','Rotina',true),
('bank-107','Month','Mês','mânth','/mʌnθ/','One month of English.','Um mês de inglês.','🗓️','Rotina',true),
('bank-108','Year','Ano','íar','/jɪr/','Happy New Year!','Feliz Ano Novo!','🎆','Rotina',true),
('bank-109','Hour','Hora','áuar','/ˈaʊər/','One more hour, please.','Mais uma hora, por favor.','⌛','Rotina',true),
('bank-110','Minute','Minuto','mínit','/ˈmɪnɪt/','Wait a minute.','Espere um minuto.','⏳','Rotina',true),
('bank-111','Day','Dia','dêi','/deɪ/','Have a nice day!','Tenha um bom dia!','☀️','Rotina',true),
('bank-112','Yesterday','Ontem','iéstârdei','/ˈjestərdeɪ/','It rained yesterday.','Choveu ontem.','🌧️','Rotina',true),
('bank-113','Monday','Segunda-feira','mândei','/ˈmʌndeɪ/','Back to work on Monday.','De volta ao trabalho segunda.','💼','Rotina',true),
('bank-114','Tuesday','Terça-feira','tiúzdei','/ˈtjuːzdeɪ/','English class on Tuesday.','Aula de inglês na terça.','📚','Rotina',true),
('bank-115','Wednesday','Quarta-feira','uénsdei','/ˈwenzdeɪ/','Soccer on Wednesday.','Futebol na quarta.','⚽','Rotina',true),
('bank-116','Thursday','Quinta-feira','thârsdei','/ˈθɜːrzdeɪ/','Meeting on Thursday.','Reunião na quinta.','📝','Rotina',true),
('bank-117','Friday','Sexta-feira','fráidei','/ˈfraɪdeɪ/','Friday night pizza!','Pizza na sexta à noite!','🍕','Rotina',true),
('bank-118','Saturday','Sábado','sérârdei','/ˈsætərdeɪ/','Beach on Saturday.','Praia no sábado.','🏖️','Rotina',true),
('bank-119','Sunday','Domingo','sândei','/ˈsʌndeɪ/','Family lunch on Sunday.','Almoço em família no domingo.','🍛','Rotina',true),
('bank-120','Man','Homem','mén','/mæn/','A tall man arrived.','Um homem alto chegou.','👨','Pessoas',true),
('bank-121','Woman','Mulher','uúman','/ˈwʊmən/','A kind woman helped me.','Uma mulher gentil me ajudou.','👩','Pessoas',true),
('bank-122','Child','Criança','tcháild','/tʃaɪld/','Every child loves stories.','Toda criança ama histórias.','🧒','Pessoas',true),
('bank-123','Baby','Bebê','bêibi','/ˈbeɪbi/','The baby is sleeping.','O bebê está dormindo.','👶','Pessoas',true),
('bank-124','Boy','Menino','bói','/bɔɪ/','The boy plays ball.','O menino joga bola.','👦','Pessoas',true),
('bank-125','Girl','Menina','gârl','/ɡɜːrl/','The girl reads books.','A menina lê livros.','👧','Pessoas',true),
('bank-126','Mother','Mãe','mâder','/ˈmʌðər/','My mother cooks well.','Minha mãe cozinha bem.','🤱','Pessoas',true),
('bank-127','Father','Pai','fáder','/ˈfɑːðər/','My father works hard.','Meu pai trabalha muito.','👨‍👧','Pessoas',true),
('bank-128','Brother','Irmão','brâder','/ˈbrʌðər/','My brother is funny.','Meu irmão é engraçado.','🧑‍🤝‍🧑','Pessoas',true),
('bank-129','Sister','Irmã','síster','/ˈsɪstər/','My sister sings well.','Minha irmã canta bem.','👭','Pessoas',true),
('bank-130','Son','Filho','sân','/sʌn/','My son is five.','Meu filho tem cinco anos.','👦','Pessoas',true),
('bank-131','Daughter','Filha','dórer','/ˈdɔːtər/','My daughter draws well.','Minha filha desenha bem.','👧','Pessoas',true),
('bank-132','Doctor','Médico(a)','dóctor','/ˈdɒktər/','See a doctor soon.','Vá ao médico logo.','🩺','Pessoas',true),
('bank-133','Teacher','Professor(a)','títcher','/ˈtiːtʃər/','My teacher is patient.','Meu professor é paciente.','🧑‍🏫','Pessoas',true),
('bank-134','Internet','Internet','ínternet','/ˈɪntərnet/','The internet is slow.','A internet está lenta.','🌐','Tech',true),
('bank-135','Email','E-mail','ímêiu','/ˈiːmeɪl/','Send me an email.','Me mande um e-mail.','📧','Tech',true),
('bank-136','Password','Senha','pésuord','/ˈpæswɜːrd/','Choose a strong password.','Escolha uma senha forte.','🔐','Tech',true),
('bank-137','Screen','Tela','scrín','/skriːn/','Look at the screen.','Olhe para a tela.','🖥️','Tech',true),
('bank-138','Keyboard','Teclado','kíbord','/ˈkiːbɔːrd/','Type on the keyboard.','Digite no teclado.','⌨️','Tech',true),
('bank-139','App','Aplicativo','ép','/æp/','This app is amazing.','Este app é incrível.','📲','Tech',true),
('bank-140','Website','Site','uébsait','/ˈwebsaɪt/','Visit our website.','Visite nosso site.','💻','Tech',true),
('bank-141','Photo','Foto','fôurou','/ˈfoʊtoʊ/','Take a photo!','Tire uma foto!','📸','Tech',true),
('bank-142','Video','Vídeo','vídiou','/ˈvɪdioʊ/','Watch this video.','Assista este vídeo.','🎥','Tech',true),
('bank-143','Message','Mensagem','méssedge','/ˈmesɪdʒ/','Send a message.','Mande uma mensagem.','💌','Tech',true),
('bank-144','Call','Ligação / Chamar','cól','/kɔːl/','I will call you.','Vou te ligar.','📞','Tech',true),
('bank-145','Battery','Bateria','béreri','/ˈbætəri/','My battery is low.','Minha bateria está fraca.','🔋','Tech',true),
('bank-146','Charger','Carregador','tchárdger','/ˈtʃɑːrdʒər/','Bring your charger.','Traga seu carregador.','🔌','Tech',true),
('bank-147','Laptop','Notebook','léptop','/ˈlæptɒp/','Work on your laptop.','Trabalhe no seu notebook.','💻','Tech',true),
('bank-148','Good','Bom / Boa','gûd','/ɡʊd/','Have a good day.','Tenha um bom dia.','👍','Adjetivos',true),
('bank-149','Bad','Ruim','béd','/bæd/','It was a bad day.','Foi um dia ruim.','👎','Adjetivos',true),
('bank-150','New','Novo(a)','niú','/njuː/','I have a new phone.','Tenho um celular novo.','🆕','Adjetivos',true),
('bank-151','Old','Velho(a)','ôuld','/oʊld/','My car is old.','Meu carro é velho.','🏚️','Adjetivos',true),
('bank-152','Young','Jovem','iân','/jʌŋ/','She is young.','Ela é jovem.','🧑','Adjetivos',true),
('bank-153','Hot','Quente','rót','/hɒt/','The soup is hot.','A sopa está quente.','🥵','Adjetivos',true),
('bank-154','Cold','Frio(a)','côuld','/koʊld/','Cold water, please.','Água fria, por favor.','🥶','Adjetivos',true),
('bank-155','Tall','Alto(a)','tól','/tɔːl/','He is very tall.','Ele é muito alto.','🦒','Adjetivos',true),
('bank-156','Long','Comprido / Longo','lón','/lɒŋ/','A long trip ahead.','Uma longa viagem pela frente.','📏','Adjetivos',true),
('bank-157','High','Alto (altura)','rái','/haɪ/','A very high mountain.','Uma montanha muito alta.','⛰️','Adjetivos',true),
('bank-158','Low','Baixo','lôu','/loʊ/','Prices are low today.','Os preços estão baixos hoje.','📉','Adjetivos',true),
('bank-159','Strong','Forte','strón','/strɒŋ/','Drink strong coffee.','Beba café forte.','💪','Adjetivos',true),
('bank-160','Weak','Fraco(a)','uík','/wiːk/','Weak signal here.','Sinal fraco aqui.','📶','Adjetivos',true),
('bank-161','Rich','Rico(a)','rítch','/rɪtʃ/','A rich dessert.','Uma sobremesa rica.','💎','Adjetivos',true),
('bank-162','Poor','Pobre','púr','/pʊr/','Poor lighting here.','Iluminação fraca aqui.','🕯️','Adjetivos',true),
('bank-163','Clean','Limpo(a)','clín','/kliːn/','Keep it clean.','Mantenha limpo.','✨','Adjetivos',true),
('bank-164','Dirty','Sujo(a)','dârti','/ˈdɜːrti/','Dirty shoes outside.','Sapatos sujos lá fora.','🧼','Adjetivos',true),
('bank-165','Full','Cheio(a)','fûl','/fʊl/','My bag is full.','Minha bolsa está cheia.','🎒','Adjetivos',true),
('bank-166','Empty','Vazio(a)','émpti','/ˈempti/','The glass is empty.','O copo está vazio.','🥛','Adjetivos',true),
('bank-167','Heavy','Pesado(a)','révi','/ˈhevi/','This box is heavy.','Esta caixa está pesada.','🏋️','Adjetivos',true),
('bank-168','Dark','Escuro(a)','dárk','/dɑːrk/','It is getting dark.','Está escurecendo.','🌑','Adjetivos',true),
('bank-169','Quiet','Silencioso','kuáiet','/ˈkwaɪət/','A quiet place to read.','Um lugar calmo para ler.','🤫','Adjetivos',true),
('bank-170','Noisy','Barulhento','nóizi','/ˈnɔɪzi/','A noisy street.','Uma rua barulhenta.','🔊','Adjetivos',true),
('bank-171','Sun','Sol','sân','/sʌn/','The sun is shining.','O sol está brilhando.','☀️','Natureza',true),
('bank-172','Moon','Lua','mún','/muːn/','A full moon tonight.','Lua cheia hoje à noite.','🌕','Natureza',true),
('bank-173','Star','Estrela','stár','/stɑːr/','Count the stars.','Conte as estrelas.','⭐','Natureza',true),
('bank-174','Sky','Céu','skái','/skaɪ/','A blue sky today.','Um céu azul hoje.','🌤️','Natureza',true),
('bank-175','Cloud','Nuvem','cláud','/klaʊd/','Dark clouds coming.','Nuvens escuras chegando.','☁️','Natureza',true),
('bank-176','Rain','Chuva','rêin','/reɪn/','Take an umbrella, rain soon.','Leve guarda-chuva, vai chover.','🌧️','Natureza',true),
('bank-177','Wind','Vento','uínd','/wɪnd/','A strong wind today.','Um vento forte hoje.','💨','Natureza',true),
('bank-178','River','Rio','ríver','/ˈrɪvər/','Swim in the river.','Nade no rio.','🏞️','Natureza',true),
('bank-179','Sea','Mar','sí','/siː/','The sea is calm.','O mar está calmo.','🌊','Natureza',true),
('bank-180','Mountain','Montanha','mâunten','/ˈmaʊntən/','Climb the mountain.','Escale a montanha.','🏔️','Natureza',true),
('bank-181','Tree','Árvore','trí','/triː/','A tall green tree.','Uma árvore alta e verde.','🌳','Natureza',true),
('bank-182','Flower','Flor','fláuar','/ˈflaʊər/','A flower for you.','Uma flor para você.','🌸','Natureza',true),
('bank-183','Bird','Pássaro','bârd','/bɜːrd/','Birds sing early.','Pássaros cantam cedo.','🐦','Natureza',true),
('bank-184','Lake','Lago','lêik','/leɪk/','A quiet lake nearby.','Um lago calmo por perto.','🏖️','Natureza',true),
('bank-185','Forest','Floresta','fórest','/ˈfɒrɪst/','The Amazon forest is huge.','A floresta amazônica é imensa.','🌲','Natureza',true),
('bank-186','Head','Cabeça','réd','/hed/','My head hurts.','Minha cabeça dói.','🤕','Corpo',true),
('bank-187','Eye','Olho','ái','/aɪ/','Close your eyes.','Feche os olhos.','👁️','Corpo',true),
('bank-188','Ear','Ouvido / Orelha','íar','/ɪr/','Dogs have good ears.','Cachorros têm bons ouvidos.','👂','Corpo',true),
('bank-189','Nose','Nariz','nôuz','/noʊz/','A runny nose in winter.','Nariz escorrendo no inverno.','👃','Corpo',true),
('bank-190','Mouth','Boca','máulth','/maʊθ/','Open your mouth.','Abra a boca.','👄','Corpo',true),
('bank-191','Hand','Mão','rénd','/hænd/','Wash your hands.','Lave as mãos.','🤲','Corpo',true),
('bank-192','Foot','Pé','fût','/fʊt/','My foot hurts.','Meu pé dói.','🦶','Corpo',true),
('bank-193','Arm','Braço','árm','/ɑːrm/','Strong arms lift more.','Braços fortes levantam mais.','💪','Corpo',true),
('bank-194','Leg','Perna','lég','/leɡ/','Stretch your legs.','Alongue as pernas.','🦵','Corpo',true),
('bank-195','Heart','Coração','rárt','/hɑːrt/','Follow your heart.','Siga seu coração.','❤️','Corpo',true),
('bank-196','Hair','Cabelo','rér','/her/','I cut my hair.','Cortei meu cabelo.','💇','Corpo',true),
('bank-197','Tooth','Dente','túth','/tuːθ/','Brush your teeth.','Escove os dentes.','🦷','Corpo',true),
('bank-198','Back','Costas','bék','/bæk/','Sit with a straight back.','Sente-se com as costas retas.','🧍','Corpo',true),
('bank-199','Body','Corpo','bódi','/ˈbɒdi/','Take care of your body.','Cuide do seu corpo.','🏃','Corpo',true),
('bank-200','Shirt','Camisa','chârt','/ʃɜːrt/','A white shirt, please.','Uma camisa branca, por favor.','👔','Roupas',true),
('bank-201','Pants','Calça','pénts','/pænts/','New jeans pants.','Calça jeans nova.','👖','Roupas',true),
('bank-202','Dress','Vestido','drés','/dres/','A red dress for tonight.','Um vestido vermelho para hoje.','👗','Roupas',true),
('bank-203','Shoes','Sapatos','chúus','/ʃuːz/','Comfortable shoes help.','Sapatos confortáveis ajudam.','👟','Roupas',true),
('bank-204','Hat','Chapéu / Boné','rét','/hæt/','Wear a hat in the sun.','Use chapéu no sol.','🧢','Roupas',true),
('bank-205','Jacket','Jaqueta','dchéquet','/ˈdʒækɪt/','Take a jacket, it is cold.','Leve uma jaqueta, está frio.','🧥','Roupas',true),
('bank-206','Socks','Meias','sóks','/sɒks/','Warm socks for winter.','Meias quentes para o inverno.','🧦','Roupas',true),
('bank-207','Glasses','Óculos','gléssiz','/ˈɡlæsɪz/','I forgot my glasses.','Esqueci meus óculos.','👓','Roupas',true),
('bank-208','Watch','Relógio (pulso)','uótch','/wɒtʃ/','What a nice watch!','Que relógio bonito!','⌚','Roupas',true),
('bank-209','Bag','Bolsa / Mochila','bég','/bæɡ/','My bag is full.','Minha bolsa está cheia.','👜','Roupas',true),
('bank-210','Coat','Casaco','côut','/koʊt/','A warm winter coat.','Um casaco quente de inverno.','🧥','Roupas',true),
('bank-211','Shorts','Bermuda / Short','chórts','/ʃɔːrts/','Shorts for the beach.','Bermuda para a praia.','🩳','Roupas',true),
('bank-212','Give up','Desistir','guív âp','/ɡɪv ʌp/','Never give up on English!','Nunca desista do inglês!','🏳️','Phrasal Verbs',true),
('bank-213','Look after','Cuidar de','lûk éfter','/lʊk ˈæftər/','She looks after her little brother.','Ela cuida do irmãozinho.','🤱','Phrasal Verbs',true),
('bank-214','Run into','Encontrar por acaso','rân íntu','/rʌn ˈɪntuː/','I ran into an old friend downtown.','Encontrei um velho amigo no centro por acaso.','🤝','Phrasal Verbs',true),
('bank-215','Take off','Decolar / Tirar (roupa)','têik óf','/teɪk ɒf/','The plane takes off at six.','O avião decola às seis.','🛫','Phrasal Verbs',true),
('bank-216','Put off','Adiar','pût óf','/pʊt ɒf/','Don’t put off your studies.','Não adie seus estudos.','📅','Phrasal Verbs',true),
('bank-217','Get along','Dar-se bem','guét alón','/ɡet əˈlɒŋ/','They get along very well.','Eles se dão muito bem.','😊','Phrasal Verbs',true),
('bank-218','Break down','Quebrar (máquina) / Desabar','brêik dáun','/breɪk daʊn/','My car broke down yesterday.','Meu carro quebrou ontem.','🚗','Phrasal Verbs',true),
('bank-219','Turn up','Aparecer / Aumentar volume','târn âp','/tɜːrn ʌp/','He turned up late to class.','Ele apareceu atrasado na aula.','🔊','Phrasal Verbs',true),
('bank-220','Turn down','Recusar / Abaixar volume','târn dáun','/tɜːrn daʊn/','She turned down the job offer.','Ela recusou a oferta de emprego.','👎','Phrasal Verbs',true),
('bank-221','Bring up','Mencionar / Criar (filho)','brín âp','/brɪŋ ʌp/','He brought up a good idea.','Ele mencionou uma boa ideia.','💡','Phrasal Verbs',true),
('bank-222','Call off','Cancelar','cól óf','/kɔːl ɒf/','They called off the meeting.','Eles cancelaram a reunião.','❌','Phrasal Verbs',true),
('bank-223','Carry on','Continuar','kéri ón','/ˈkæri ɒn/','Carry on with your work.','Continue com seu trabalho.','➡️','Phrasal Verbs',true),
('bank-224','Come across','Deparar-se com','câm acróss','/kʌm əˈkrɒs/','I came across a great book.','Deparei-me com um ótimo livro.','📖','Phrasal Verbs',true),
('bank-225','Cut down','Reduzir / Cortar','cât dáun','/kʌt daʊn/','Cut down on sugar.','Reduza o açúcar.','✂️','Phrasal Verbs',true),
('bank-226','Deal with','Lidar com','díl uíd','/diːl wɪð/','I deal with customers daily.','Lido com clientes todo dia.','🤝','Phrasal Verbs',true),
('bank-227','Figure out','Descobrir / Entender','fíguer áut','/ˈfɪɡər aʊt/','I figured out the answer!','Descobri a resposta!','🧩','Phrasal Verbs',true),
('bank-228','Find out','Descobrir (informação)','fáind áut','/faɪnd aʊt/','Find out the train time.','Descubra o horário do trem.','🔍','Phrasal Verbs',true),
('bank-229','Get over','Superar','guét ôuver','/ɡet ˈoʊvər/','You will get over it.','Você vai superar isso.','💪','Phrasal Verbs',true),
('bank-230','Give back','Devolver','guív bék','/ɡɪv bæk/','Give me back my book.','Devolva meu livro.','📚','Phrasal Verbs',true),
('bank-231','Go on','Continuar / Acontecer','gôu ón','/ɡoʊ ɒn/','The show must go on.','O show deve continuar.','🎭','Phrasal Verbs',true),
('bank-232','Grow up','Crescer','grôu âp','/ɡroʊ ʌp/','I grew up in Bahia.','Cresci na Bahia.','🌱','Phrasal Verbs',true),
('bank-233','Hang out','Sair / Passar tempo junto','réng áut','/hæŋ aʊt/','We hang out on weekends.','Saímos juntos nos fins de semana.','🧑‍🤝‍🧑','Phrasal Verbs',true),
('bank-234','Hold on','Esperar / Segurar','rôuld ón','/hoʊld ɒn/','Hold on a minute!','Espere um minuto!','✋','Phrasal Verbs',true),
('bank-235','Keep up','Acompanhar o ritmo','kíp âp','/kiːp ʌp/','Keep up the good work!','Continue o bom trabalho!','🏃','Phrasal Verbs',true),
('bank-236','Look forward to','Aguardar com ansiedade','lûk fóruard tu','/lʊk ˈfɔːrwərd tuː/','I look forward to the trip.','Mal posso esperar pela viagem.','✈️','Phrasal Verbs',true),
('bank-237','Look up','Consultar / Melhorar','lûk âp','/lʊk ʌp/','Look up the word online.','Consulte a palavra online.','📱','Phrasal Verbs',true),
('bank-238','Make up','Inventar / Fazer as pazes','mêik âp','/meɪk ʌp/','They made up after the fight.','Eles fizeram as pazes após a briga.','🫂','Phrasal Verbs',true),
('bank-239','Pick up','Buscar / Pegar','pík âp','/pɪk ʌp/','Pick me up at eight.','Venha me buscar às oito.','🚗','Phrasal Verbs',true),
('bank-240','Point out','Apontar / Destacar','póint áut','/pɔɪnt aʊt/','She pointed out my mistake.','Ela apontou meu erro.','👉','Phrasal Verbs',true),
('bank-241','Put on','Vestir / Ligar','pût ón','/pʊt ɒn/','Put on your jacket.','Vista sua jaqueta.','🧥','Phrasal Verbs',true),
('bank-242','Put up with','Tolerar','pût âp uíd','/pʊt ʌp wɪð/','I can’t put up with noise.','Não tolero barulho.','😤','Phrasal Verbs',true),
('bank-243','Run out of','Ficar sem','rân áut óv','/rʌn aʊt ɒv/','We ran out of milk.','Ficamos sem leite.','🥛','Phrasal Verbs',true),
('bank-244','Set up','Montar / Organizar','sét âp','/set ʌp/','Set up your new phone.','Configure seu celular novo.','🔧','Phrasal Verbs',true),
('bank-245','Show up','Aparecer','chôu âp','/ʃoʊ ʌp/','Nobody showed up.','Ninguém apareceu.','👀','Phrasal Verbs',true),
('bank-246','Throw away','Jogar fora','thrôu auêi','/θroʊ əˈweɪ/','Throw away old papers.','Jogue papéis velhos fora.','🗑️','Phrasal Verbs',true),
('bank-247','Try on','Provar (roupa)','trái ón','/traɪ ɒn/','Try on these shoes.','Prove estes sapatos.','👟','Phrasal Verbs',true),
('bank-248','Work out','Exercitar-se / Dar certo','uórk áut','/wɜːrk aʊt/','I work out three times a week.','Malho três vezes por semana.','🏋️','Phrasal Verbs',true),
('bank-249','Check in','Fazer check-in','tchék ín','/tʃek ɪn/','Check in two hours early.','Faça check-in com duas horas de antecedência.','🛂','Phrasal Verbs',true),
('bank-250','Drop off','Deixar (alguém em lugar)','dróp óf','/drɒp ɒf/','Drop me off at school.','Me deixe na escola.','🏫','Phrasal Verbs',true),
('bank-251','Fill out','Preencher (formulário)','fíl áut','/fɪl aʊt/','Fill out this form.','Preencha este formulário.','📝','Phrasal Verbs',true),
('bank-252','Let down','Decepcionar','lét dáun','/let daʊn/','Don’t let me down.','Não me decepcione.','😞','Phrasal Verbs',true),
('bank-253','Pass away','Falecer','péss auêi','/pæs əˈweɪ/','Her grandfather passed away.','O avô dela faleceu.','🕊️','Phrasal Verbs',true),
('bank-254','Take over','Assumir','têik ôuver','/teɪk ˈoʊvər/','She took over the project.','Ela assumiu o projeto.','📊','Phrasal Verbs',true),
('bank-255','Watch out','Cuidado!','uótch áut','/wɒtʃ aʊt/','Watch out for cars!','Cuidado com os carros!','⚠️','Phrasal Verbs',true),
('bank-256','Back up','Apoiar / Fazer backup','bék âp','/bæk ʌp/','Back up your files daily.','Faça backup dos arquivos todo dia.','💾','Phrasal Verbs',true),
('bank-257','Calm down','Acalmar-se','cám dáun','/kɑːm daʊn/','Calm down and breathe.','Acalme-se e respire.','😌','Phrasal Verbs',true)
ON CONFLICT (bank_id) DO NOTHING;
